# Climate-Friendly Food Systems (CFFS) Labelling Project

### The University of British Columbia

#### Created by Silvia Huang, CFFS Data Analyst
***

## Part III: Update Information and Mapping

# Climate-Friendly Food Systems (CFFS) Labelling Project

### The University of British Columbia

#### Created by Silvia Huang, CFFS Data Analyst
***

## Part III: Update Information and Mapping

## Set up and Import Libraries

In [1]:
#pip install -r requirements.txt

In [1]:
import numpy as np
import pandas as pd
import pdpipe as pdp
import matplotlib.pyplot as plt
import glob
import os
import csv
from itertools import islice
from decimal import Decimal
import xml.etree.ElementTree as et
from xml.etree.ElementTree import parse
import openpyxl
import pytest
from datetime import datetime

/Users/jennylee/opt/anaconda3/lib/python3.9/site-packages/pdpipe/col_generation.py:12: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

In [2]:
# Set the root path, change the the current working directory into the project folder
path = os.getcwd()
os.chdir(path)

In [3]:
# Enable reading data table in the scrolling window if you prefer
pd.set_option("display.max_rows", None, "display.max_columns", None)

***
## Import Preprocessed Datasets

In [5]:
Preps = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "Preps_Unit_Cleaned.csv"))
Preps.head()

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-50310,BATTER|Pancake|Carrot Cake,5.0,L,PREP,5000.0,ml
1,P-50317,BATTER|Pancake|Lemon Poppyseed,5.0,L,PREP,5000.0,ml
2,P-28285,BATTER|Pancakes,4.8,Kg,PREP,4800.0,g
3,P-50739,COMPOTE|Apple Cinnamon,2.5,L,PREP,2500.0,ml
4,P-26063,COMPOTE|Blueberry,2.6,L,PREP,2600.0,ml

In [6]:
ghge_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "ghge_factors.csv"))
ghge_factors.head()

,Category ID,Food Category,Active Total Supply Chain Emissions (kg CO2 / kg food)
0,1,beef & buffalo meat,41.3463
1,2,lamb/mutton & goat meat,41.6211
2,3,pork (pig meat),9.8315
3,4,"poultry (chicken, turkey)",4.3996
4,5,butter,11.4316

In [7]:
nitro_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "nitrogen_factors.csv"))
nitro_factors.head()

   Category ID              Food Category  g N lost/kg product
0            1        beef & buffalo meat               329.50
1            2    lamb/mutton & goat meat               231.15
2            3            pork (pig meat)               132.80
3            4  poultry (chicken, turkey)               116.80
4            5                     butter               100.35

In [8]:
water_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "water_factors.csv"))
water_factors.head()

,Category ID,Food Category,Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
0,1,beef & buffalo meat,1677.200,61309.000
1,2,lamb/mutton & goat meat,461.200,258.900
2,3,pork (pig meat),1810.300,54242.700
3,4,"poultry (chicken, turkey)",370.300,333.500
4,5,butter,1010.176,50055.168

In [9]:
# Load current Items List with assigned Emission Factors Category ID
Items_Assigned = pd.read_csv(os.path.join(os.getcwd(), "data", "mapping", "Items_List_Assigned.csv"))
Items_Assigned.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-57545,1,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT
1,I-10869,1,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT
2,I-7064,1,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT
3,I-37005,1,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT
4,I-37002,1,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT

***
## Import Update Info

In [10]:
# Import list of prep that need convert uom to standard uom manually
Manual_PrepU = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "update", "Preps_UpdateUom.csv"))
Manual_PrepU.head()

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-54697,LEMON|Wedge 1/8,8.0,each,PREP,84.0,g
1,P-35132,MARINATED|Lemon & Herb Chx,185.0,ea,PREP,24050.0,g
2,P-51992,YIELD|Bread|Sourdough 5/8,36.0,slice,NaN,1620.0,g
3,P-26234,BATCH|Roasted Garlic Bread,16.0,ea,PREP,1280.0,g
4,P-26170,GRILLED|NaanBread,1.0,ea,PREP,125.0,g

In [11]:
# Select the file path for new items list with category id
New_Items_Added = pd.read_csv(os.path.join(os.getcwd(), "data", "mapping", "new items added", "New_Items_Added_10.csv"))
New_Items_Added

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-13791,24,BAR GF NANAIMO 3X3 WRAPPED,12,CT,1.00,CT,BAKED GOODS
1,I-63679,24,BUTTERHORNS EACH,1,ea,1.00,ea,BAKED GOODS
2,I-31545,24,CAKE CARROT CARM STACK,48,slice,1.00,slice,BAKED GOODS
3,I-1057,24,CAKE CHOC TRIPLE TIGER 12X16IN,2,SHEET,1.00,SHEET,BAKED GOODS
4,I-60871,24,CAKE SHEET CHOC LAYER 12X16IN,2,SHEET,1.00,SHEET,BAKED GOODS
5,I-29698,24,"CHEESECAKE 2"" MINI",40,ea,1.00,ea,BAKED GOODS
6,I-1392,24,COOKIE GF GINGER VEGAN,12,CT,1.00,CT,BAKED GOODS
7,I-63680,24,POPPYHORNS,1,ea,1.00,ea,BAKED GOODS
8,I-1250,24,PRETZEL PIZZA EACH,1,ea,1.00,CT,BAKED GOODS
9,I-3771,55,YERBA MATE TEA ORG TRADITIONAL,6,lb,1.00,lb,BEVERAGE
10,I-1790,55,JUICE APPLE 100% UNSWT TETRA,40,PTN,1.00,PTN,BEVERAGE
11,I-19634,24,LOAF FRENCH BREAD,1,ea,1.00,LOAF,BREAD
12,I-2309,3,HAM FESTIVE,1,Kg,1.00,Kg,DELI & PREPARED MEAT
13,I-3125,21,CEREAL RICE KRISPIE SQ,6,ea,1.00,ea,FOOD - GROCERY
14,I-37470,22,CORN HOMINY,6,LG CAN,2835.00,g,FOOD - GROCERY
15,I-19540,54,FENUGREEK LEAVES DRY,454,g,1.00,g,FOOD - GROCERY
16,I-3397,31,OLIVE RIPE BLACK SLCD,6,LG CAN,2.84,L,FOOD - GROCERY
17,I-3506,58,SAUCE BBQ SMOKEY TFC,2,JUG,3.78,L,FOOD - GROCERY
18,I-3540,58,SAUCE SAMBAL OELEK,3,jar,3500.00,L,FOOD - GROCERY
19,I-3110,20,TOFU EXTRA FIRM GREEN,12,pak,350.00,g,FOOD - GROCERY
20,I-2949,37,TOMATO SAN MARZANO LA REGINA,6,LG CAN,100.00,fl oz,FOOD - GROCERY
21,I-37475,40,PASTE ACHIOTE,110,g,1.00,g,FOOD - GROCERY
22,I-36996,59,"SANDWICH BACON, CHEDD & TOMATO",1,ea,1.00,ea,FOOD - GROCERY
23,I-36999,59,SANDWICH CASATA FALAFEL,1,ea,1.00,ea,FOOD - GROCERY
24,I-36998,59,SANDWICH CHICKEN CRANCHERRY,1,ea,1.00,ea,FOOD - GROCERY
25,I-36995,59,SANDWICH EGG SALAD,1,ea,1.00,ea,FOOD - GROCERY
26,I-37000,59,SANDWICH HAM & CHEESE,1,ea,1.00,ea,FOOD - GROCERY
27,I-36997,59,SANDWICH SALMON SALAD,1,ea,1.00,ea,FOOD - GROCERY
28,I-38987,59,WRAP BREAKFAST HAM & CHEESE,1,ea,1.00,ea,FOOD - GROCERY
29,I-38988,59,WRAP BREAKFAST MEDITERRANEAN,1,ea,1.00,ea,FOOD - GROCERY
30,I-3912,18,BURGER VEGGIE 44CT FZN,44,CT,1.00,CT,MEAT
31,I-3852,3,PORK BUTT SHLDR BNLS N/NFR,1,Kg,1.00,Kg,MEAT
32,I-22915,3,PORK FEET CUT,1,Kg,1.00,Kg,MEAT
33,I-64876,18,TMRW BURGER PATTIES VEGAN,40,each,1.00,each,MEAT
34,I-64877,3,TMRW SAUSAGE BREAKFAST PATTY,100,each,1.00,ea,MEAT
35,I-55331,4,CHICK BREAST BL/SO HAL TENDOUT,1,Kg,1.00,Kg,POULTRY
36,I-3999,4,CHICK DRUMSTICK HALAL,1,Kg,1.00,Kg,POULTRY
37,I-4465,36,ASPARAGUS (LARGE) MX,11,lb,1.00,lb,PRODUCE
38,I-22443,40,BAMBOO SHOOTS STRIP,6,LG CAN,2.84,L,PRODUCE
39,I-10616,17,BEANS ROMANO,1,lb,1.00,lb,PRODUCE
40,I-4582,38,CARROTS BABY BUNCHED BC,1,each,1.00,CT,PRODUCE
41,I-11670,40,COLESLAW MIX CABBAGE&CARROT,5,lb,1.00,lb,PRODUCE
42,I-10265,37,TOMATOES HEIRLOOM BC,1,lb,1.00,lb,PRODUCE
43,I-4849,36,SALAD MIX ARTISAN,3,bag,2.00,lb,PRODUCE
44,I-62863,59,CK|G&G|HMR|Meat Ball & Pasta.,1,ea,1.00,ea,PRODUCTION FOOD
45,I-19923,12,HALIBUT STEAK 4OZ.OW,1,lb,1.00,lb,SEAFOOD
46,I-8105,12,SAL LOX SMK SLC OW,1,lb,1.00,lb,SEAFOOD
47,I-3094,54,PEPPERCORN BLACK WHOLE,3,Kg,1.00,Kg,SPICES
48,I-16060,54,SUMAC GROUND,1,each,454.00,g,SPICES

In [12]:
# Import list of items that adjusted GHGe factor manually
Manual_Factor = pd.read_csv(os.path.join(os.getcwd(), "data", "mapping", "Manual_Adjust_Factors.csv"))
Manual_Factor.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
0,I-52090,59,BURGER BEEF & MUSHROOM HALAL,1.0,cs,48.00,CT,MEAT,25.00894,200.86,1038.84,37961.2
1,I-45558,59,Prep-Vegan Parmesan,1000.0,g,1.00,g,PRODUCTION FOOD,3.85686,0.00,0.00,0.0
2,I-3352,59,MAYONNAISE PAIL TFC 4L,2.0,each,4.00,L,FOOD - GROCERY,3.55000,0.00,0.00,0.0
3,I-3223,59,COCONUT MILK 17/19% MILK FAT,6.0,LG CAN,2.84,L,FOOD - GROCERY,3.50000,0.00,1.00,1.0
4,I-2898,59,MUSTARD DIJON WINE FLEUR,6.0,jar,1.00,Kg,FOOD - GROCERY,3.32600,0.00,0.00,0.0

### Update Correct Uom for Preps

In [13]:
# Update prep list with manully adjusted uom
for index, row in Manual_PrepU.iterrows():
    PrepId = Manual_PrepU.loc[index, 'PrepId']
    qty = Manual_PrepU.loc[index, 'StdQty']
    uom = Manual_PrepU.loc[index, 'StdUom']
    Preps.loc[Preps['PrepId'] == PrepId, 'StdQty'] = qty
    Preps.loc[Preps['PrepId'] == PrepId, 'StdUom'] = uom

In [14]:
Preps.drop_duplicates(subset=['PrepId'], inplace=True,)

In [15]:
Preps.head()

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-55516,BAKED|Lasagna|Spin Mushroom,5.550,Kg,NaN,5550.0,g
1,P-54666,BAKED|Pasta|Chicken Alfredo,6.176,Kg,NaN,6176.0,g
2,P-54664,BAKED|Pasta|Chorizo Penne,7.360,Kg,NaN,7360.0,g
3,P-56502,BAKED|Pasta|Shrimp Pesto,5.760,Kg,NaN,5760.0,g
4,P-56433,BATCH|Shrimp Remoulade,1.600,Kg,NaN,1600.0,g

In [16]:
Preps.shape

(752, 7)

In [17]:
path = os.path.join(os.getcwd(), "data", "cleaning", "Preps_List_Cleaned.csv")
Preps.to_csv(path, index = False, header = True)

### Import List of New Items with Emission Factors Category ID Assigned

In [18]:
frames = [Items_Assigned, New_Items_Added]
Items_Assigned_Updated = pd.concat(frames).reset_index(drop=True, inplace=False).drop_duplicates()
Items_Assigned_Updated.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-57545,1,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT
1,I-10869,1,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT
2,I-7064,1,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT
3,I-37005,1,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT
4,I-37002,1,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT

In [19]:
Items_Assigned_Updated.shape

(1993, 8)

In [20]:
Items_Assigned_Updated[['CategoryID']] = Items_Assigned_Updated[['CategoryID']].apply(pd.to_numeric)

In [21]:
path = os.path.join(os.getcwd(), "data", "mapping", "Items_List_Assigned.csv")
Items_Assigned_Updated.to_csv(path, index = False, header = True)

## Mapping Items to Footprint Factors

In [22]:
# Map GHG footprint factors
mapping = pd.merge(Items_Assigned_Updated, ghge_factors.loc[:,['Category ID','Food Category','Active Total Supply Chain Emissions (kg CO2 / kg food)']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')
for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'Active Total Supply Chain Emissions (kg CO2 / kg food)'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Active Total Supply Chain Emissions (kg CO2 / kg food)
0,I-57545,1,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,41.3463
1,I-10869,1,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,41.3463
2,I-7064,1,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,41.3463
3,I-37005,1,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,41.3463
4,I-37002,1,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,41.3463
...,...,...,...,...,...,...,...,...,...
1988,I-62863,59,CK|G&G|HMR|Meat Ball & Pasta.,1.00,ea,1.0,ea,PRODUCTION FOOD,0.0000
1989,I-19923,12,HALIBUT STEAK 4OZ.OW,1.00,lb,1.0,lb,SEAFOOD,4.9798
1990,I-8105,12,SAL LOX SMK SLC OW,1.00,lb,1.0,lb,SEAFOOD,4.9798
1991,I-3094,54,PEPPERCORN BLACK WHOLE,3.00,Kg,1.0,Kg,SPICES,9.3703
1992,I-16060,54,SUMAC GROUND,1.00,each,454.0,g,SPICES,9.3703

In [23]:
# Map nitrogen footprint factors
mapping = pd.merge(mapping, nitro_factors.loc[:,['Category ID','Food Category','g N lost/kg product']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')

for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'g N lost/kg product'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product
0,I-57545,1,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,41.3463,329.50
1,I-10869,1,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,41.3463,329.50
2,I-7064,1,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,41.3463,329.50
3,I-37005,1,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,41.3463,329.50
4,I-37002,1,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,41.3463,329.50
...,...,...,...,...,...,...,...,...,...,...
1988,I-62863,59,CK|G&G|HMR|Meat Ball & Pasta.,1.00,ea,1.0,ea,PRODUCTION FOOD,0.0000,0.00
1989,I-19923,12,HALIBUT STEAK 4OZ.OW,1.00,lb,1.0,lb,SEAFOOD,4.9798,70.30
1990,I-8105,12,SAL LOX SMK SLC OW,1.00,lb,1.0,lb,SEAFOOD,4.9798,70.30
1991,I-3094,54,PEPPERCORN BLACK WHOLE,3.00,Kg,1.0,Kg,SPICES,9.3703,6.75
1992,I-16060,54,SUMAC GROUND,1.00,each,454.0,g,SPICES,9.3703,6.75

In [24]:
# Map water footprint factors
mapping = pd.merge(mapping, water_factors.loc[:,['Category ID','Food Category','Freshwater Withdrawals (L/FU)', 'Stress-Weighted Water Use (L/FU)']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')

for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'Freshwater Withdrawals (L/FU)'] = 0
        mapping.loc[index,'Stress-Weighted Water Use (L/FU)'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
0,I-57545,1,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,41.3463,329.50,1677.2,61309.0
1,I-10869,1,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,41.3463,329.50,1677.2,61309.0
2,I-7064,1,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,41.3463,329.50,1677.2,61309.0
3,I-37005,1,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,41.3463,329.50,1677.2,61309.0
4,I-37002,1,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,41.3463,329.50,1677.2,61309.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1988,I-62863,59,CK|G&G|HMR|Meat Ball & Pasta.,1.00,ea,1.0,ea,PRODUCTION FOOD,0.0000,0.00,0.0,0.0
1989,I-19923,12,HALIBUT STEAK 4OZ.OW,1.00,lb,1.0,lb,SEAFOOD,4.9798,70.30,1580.5,8483.4
1990,I-8105,12,SAL LOX SMK SLC OW,1.00,lb,1.0,lb,SEAFOOD,4.9798,70.30,1580.5,8483.4
1991,I-3094,54,PEPPERCORN BLACK WHOLE,3.00,Kg,1.0,Kg,SPICES,9.3703,6.75,24.9,220.3
1992,I-16060,54,SUMAC GROUND,1.00,each,454.0,g,SPICES,9.3703,6.75,24.9,220.3

### Manully Adjust Footprint Factor for Specific Items

In [25]:
for index, row in Manual_Factor.iterrows():
    itemId = Manual_Factor.loc[index, 'ItemId']
    ghge = Manual_Factor.loc[index, 'Active Total Supply Chain Emissions (kg CO2 / kg food)']
    nitro = Manual_Factor.loc[index, 'g N lost/kg product']
    water = Manual_Factor.loc[index, 'Freshwater Withdrawals (L/FU)']
    str_water = Manual_Factor.loc[index, 'Stress-Weighted Water Use (L/FU)']
    mapping.loc[mapping['ItemId'] == itemId, 'Active Total Supply Chain Emissions (kg CO2 / kg food)'] = ghge
    mapping.loc[mapping['ItemId'] == itemId, 'g N lost/kg product'] = nitro
    mapping.loc[mapping['ItemId'] == itemId, 'Freshwater Withdrawals (L/FU)'] = water
    mapping.loc[mapping['ItemId'] == itemId, 'Stress-Weighted Water Use (L/FU)'] = str_water

In [26]:
mapping.drop_duplicates(subset = ['ItemId'], inplace=True)
mapping.dtypes

ItemId                                                     object
CategoryID                                                  int64
Description                                                object
CaseQty                                                   float64
CaseUOM                                                    object
PakQty                                                    float64
PakUOM                                                     object
InventoryGroup                                             object
Active Total Supply Chain Emissions (kg CO2 / kg food)    float64
g N lost/kg product                                       float64
Freshwater Withdrawals (L/FU)                             float64
Stress-Weighted Water Use (L/FU)                          float64
dtype: object

In [27]:
mapping.shape

(1993, 12)

In [28]:
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
0,I-57545,1,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,41.3463,329.50,1677.2,61309.0
1,I-10869,1,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,41.3463,329.50,1677.2,61309.0
2,I-7064,1,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,41.3463,329.50,1677.2,61309.0
3,I-37005,1,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,41.3463,329.50,1677.2,61309.0
4,I-37002,1,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,41.3463,329.50,1677.2,61309.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1988,I-62863,59,CK|G&G|HMR|Meat Ball & Pasta.,1.00,ea,1.0,ea,PRODUCTION FOOD,0.0000,0.00,0.0,0.0
1989,I-19923,12,HALIBUT STEAK 4OZ.OW,1.00,lb,1.0,lb,SEAFOOD,4.9798,70.30,1580.5,8483.4
1990,I-8105,12,SAL LOX SMK SLC OW,1.00,lb,1.0,lb,SEAFOOD,4.9798,70.30,1580.5,8483.4
1991,I-3094,54,PEPPERCORN BLACK WHOLE,3.00,Kg,1.0,Kg,SPICES,9.3703,6.75,24.9,220.3
1992,I-16060,54,SUMAC GROUND,1.00,each,454.0,g,SPICES,9.3703,6.75,24.9,220.3

In [29]:
path = os.path.join(os.getcwd(), "data", "mapping", "Mapping.csv")
mapping.to_csv(path, index = False, header = True)